# Generated by Django 5.2.6 on 2025-09-18 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
